Name=input("Enter the name")
Age=int(input("enter the Age"))
Cgpa=float(input("Enter the CGPA"))
City=input("Enter the city")
print(Name)
print(Age)
print(City)
print(Name.upper())
print(Age.upper())
print(Cgpa.upper())
print(City.upper())